# Generated by Django 5.2.1 on 2025-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
