# Generated by Django 5.2.1 on 2025-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_user_foto_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('durasi', models.CharField(max_length=20)),
                ('youtube_id', models.CharField(max_length=20)),
            ],
        ),
    ]
